.build_docker_template: &build_docker
  services:
    - docker:20.10.16-dind
  variables:
    BUILD_VOLUME: VOL_$CI_JOB_ID
  image: docker:20.10.16
  stage: prepare
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  only:
    changes:
      - docker/*
      - .gitlab-ci-build-docker.yml

build docker ledger-app-builder:
  <<: *build_docker
  script:
    - docker pull $CI_REGISTRY_IMAGE/ledger-app-builder:latest || true
    - apk add --update git
    - git clone https://github.com/LedgerHQ/ledger-app-builder.git TMP
    - cd TMP/full &&
      docker build --cache-from $CI_REGISTRY_IMAGE/ledger-app-builder:latest
                   --tag $CI_REGISTRY_IMAGE/ledger-app-builder:latest
                   --tag ledger-app-builder:latest
             .
    - docker push $CI_REGISTRY_IMAGE/ledger-app-builder:latest

build docker ledger-app-tezos-ocaml:
  <<: *build_docker
  script:
    - docker pull $CI_REGISTRY_IMAGE/ledger-app-tezos-ocaml:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/ledger-app-tezos-ocaml:latest
                   --tag $CI_REGISTRY_IMAGE/ledger-app-tezos-ocaml:latest
                   --tag ledger-app-tezos-ocaml:latest
                   -f docker/Dockerfile.ocaml
             docker
    - docker push $CI_REGISTRY_IMAGE/ledger-app-tezos-ocaml:latest
