include: '.gitlab-ci-build-docker.yml'

stages:
  - sync
  - prepare
  - generate
  - build
  - test

generate_builtin_patterns:
  image: $CI_REGISTRY_IMAGE/ledger-app-tezos-ocaml:$CI_COMMIT_REF_NAME
  stage: generate
  script:
    - make -C pattern_registry
  artifacts:
    paths:
      - app/src/parser/generated_patterns.h

generate_samples:
  image: $CI_REGISTRY_IMAGE/ledger-app-tezos-ocaml:$CI_COMMIT_REF_NAME
  stage: generate
  script:
    - mkdir -p tests/samples/micheline
    - mkdir -p tests/samples/operations
    - dune exec ./tests/generate/generate.exe micheline 1000 nanos tests/samples/micheline
    - dune exec ./tests/generate/generate.exe operations 1000 nanos tests/samples/operations
  artifacts:
    paths:
      - tests/samples

build_nanos:
  image: $CI_REGISTRY_IMAGE/ledger-app-builder:$CI_COMMIT_REF_NAME
  stage: build
  script:
    - bash -c 'make -C app BOLOS_SDK=$NANOS_SDK'
    - cd app/bin/ && tar czf ../../app_nanos.tgz .
  dependencies:
    - generate_builtin_patterns
  artifacts:
    paths:
      - app_nanos.tgz

build_nanos_dbg:
  image: $CI_REGISTRY_IMAGE/ledger-app-builder:$CI_COMMIT_REF_NAME
  stage: build
  script:
    - bash -c 'make -C app BOLOS_SDK=$NANOS_SDK DEBUG=true'
    - cd app/bin/ && tar czf ../../app_nanos_dbg.tgz .
  dependencies:
    - generate_builtin_patterns
  artifacts:
    paths:
      - app_nanos_dbg.tgz

unit:
  image: $CI_REGISTRY_IMAGE/ledger-app-tezos-ocaml:$CI_COMMIT_REF_NAME
  stage: test
  script:
    - make -C tests/unit
  dependencies:
    - generate_samples

integration_nanos_basic:
  image:
    name: ghcr.io/ledgerhq/speculos:sha-90a021a
    entrypoint: [""]
  stage: test
  dependencies:
    - build_nanos_dbg
  script:
    - apt update && apt install -y curl jq
    - SPECULOS=/speculos/speculos.py COLUMNS=80 ./tests/integration/run_test_local.sh nanos app_nanos_dbg.tgz tests/integration/nanos
  artifacts:
    paths:
      - integration_tests.json

integration_nanos_micheline_samples:
  image:
    name: ghcr.io/ledgerhq/speculos:sha-90a021a
    entrypoint: [""]
  stage: test
  dependencies:
    - build_nanos_dbg
    - generate_samples
  script:
    - apt update && apt install -y curl jq
    - SPECULOS=/speculos/speculos.py COLUMNS=80 ./tests/integration/run_test_local.sh nanos app_nanos_dbg.tgz tests/samples/micheline
  artifacts:
    paths:
      - integration_tests.json

integration_nanos_operations_samples:
  image:
    name: ghcr.io/ledgerhq/speculos:sha-90a021a
    entrypoint: [""]
  stage: test
  dependencies:
    - build_nanos_dbg
    - generate_samples
  script:
    - apt update && apt install -y curl jq
    - SPECULOS=/speculos/speculos.py COLUMNS=80 ./tests/integration/run_test_local.sh nanos app_nanos_dbg.tgz tests/samples/operations
  artifacts:
    paths:
      - integration_tests.json
