include: '.gitlab-ci-build-docker.yml'

stages:
  - prepare
  - build
  - test

.use_docker: &use_docker
  image: !reference [.use_docker_template, image]
  after_script:
    - !reference [.use_docker_template, after_script]
  before_script:
    - !reference [.use_docker_template, before_script]
    - apk add --update make

unit:
  <<: *use_docker
  stage: test
  script:
    - make unit_tests

integration:
  image:
    name: ghcr.io/ledgerhq/speculos
    entrypoint: [""]
  stage: test
  dependencies:
    - build
  script:
    - apt update && apt install -y curl jq
    - cd tests/integration && PATH=/speculos:$PATH ./run_test_local.sh nanos

build:
  <<: *use_docker
  stage: build
  script:
    - make dist
  artifacts:
    paths:
      - app_nanos.tgz
      - app_nanosp.tgz
      - app_nanox.tgz
