name: Swap feature tests

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  job_functional_tests:
    uses: spalmer25/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@develop
    with:
      repo_for_exchange: 'spalmer25/app-exchange'
      branch_for_exchange: 'd825bfceea484937f46461975af0d51940796d87'
      branch_for_tezos: ${{ github.ref }}
      run_for_devices: '["nanos", "nanosp"]'
      test_filter: '"tezos_new"'
