name: Swap feature tests

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  job_functional_tests:
    uses: functori/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@199c44811c63ce3d751c14ab55d996b166e31f02
    with:
      repo_for_exchange: 'functori/app-exchange'
      branch_for_exchange: '199c44811c63ce3d751c14ab55d996b166e31f02'
      branch_for_tezos: ${{ github.ref }}
      run_for_devices: '["nanos", "nanosp", "stax"]'
      test_filter: '"tezos_new"'
